services:
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - LOG_LEVEL=INFO
      - ENABLE_METRICS=True
      - PROMETHEUS_MULTIPROC_DIR=/tmp
