FROM python:3.12.7-bookworm

ENV UV_PROJECT_ENVIRONMENT="/usr/local/"

RUN apt update -y && \
    apt install -y make clang python3-dev libpq-dev && \
    pip install --upgrade pip

COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

COPY . /app/

RUN make install-dev

CMD ["make", "run-dev"]